AllCops:
  Exclude:
    - '**/Rakefile'
    - '**/config.ru'
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'

Metrics/LineLength:
  Enabled: false

Documentation:
  Enabled: false

EmptyLinesAroundModuleBody:
  Enabled: false

EmptyLinesAroundClassBody:
  Enabled: false

Rails:
  Enabled: true
